CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(300) NOT NULL,
    FullName NVARCHAR(120) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL
);

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Decisions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(120) NOT NULL,
    Context NVARCHAR(1000) NOT NULL,
    Category INT NOT NULL,
    ImpactWeight DECIMAL(10,4) NOT NULL,
    Confidence DECIMAL(10,4) NOT NULL,
    EmotionalIntensity DECIMAL(10,4) NOT NULL,
    OutcomeScore DECIMAL(10,4) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE EmotionalLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Intensity DECIMAL(10,4) NOT NULL,
    Trigger NVARCHAR(200) NOT NULL,
    LoggedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE HabitEntries (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    HabitName NVARCHAR(120) NOT NULL,
    Completed BIT NOT NULL,
    ConsistencyScore DECIMAL(10,4) NOT NULL,
    EntryDateUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE GoalTargets (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    TargetValue DECIMAL(18,4) NOT NULL,
    DeadlineUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE ScoreSnapshots (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    StabilityScore DECIMAL(18,4) NOT NULL,
    GrowthAccelerationIndex DECIMAL(18,4) NOT NULL,
    RiskScore DECIMAL(18,4) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE RiskProfiles (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Volatility DECIMAL(18,4) NOT NULL,
    CurrentRiskStreak INT NOT NULL,
    Tier NVARCHAR(30) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE SimulationRuns (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    NumberOfRuns INT NOT NULL,
    ProjectedP50 DECIMAL(18,4) NOT NULL,
    ProjectedP90 DECIMAL(18,4) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE SystemAuditLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(150) NOT NULL,
    MetadataJson NVARCHAR(MAX) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
